[package]
name = "certified-assets"
version = "0.1.0"
authors = ["Roman Kashitsyn <roman@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk = "0.2.4"
ic-cdk-macros = "0.2"
ic-types = "0.1.1"
num-traits = "0.2.14"
serde = "1"
serde_bytes = "0.11"
sha2 = "0.9.1"

[profile.release]
lto = true
opt-level = 'z'
